### ISSUE TITLE
v2 incompatibility with go.mod

### ISSUE THREAD

**Issue by thomasvvugt** [valyala/fasthttp#815]
Hi fasthttp,

Nice work on releasing v2.0.0!
However, I cannot get it to work using Go Modules.
I have tried two methods, but both of them failed.

**Method 1:**
go.mod
```
module fasthttptest

go 1.14

require (
	github.com/valyala/fasthttp v2.0.0
)
```

Compilation error
```
go: errors parsing go.mod:
~/go/src/fasthttptest/go.mod:6: require github.com/valyala/fasthttp: version "v2.0.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

**Method 2:**
go.mod
```
module fasthttptest

go 1.14

require (
	github.com/valyala/fasthttp/v2 v2.0.0
)
```

Compilation error
```
go: github.com/valyala/fasthttp/v2@v2.0.0: go.mod has non-.../v2 module path "github.com/valyala/fasthttp" (and .../v2/go.mod does not exist) at revision v2.0.0
```

Would you be able to fix this issue for Go Modules?
Related blog post from Go: https://blog.golang.org/v2-go-modules

Thanks in advance! 🎉

**Comment by erikdubbelboer** [comment]
I was unaware that go doesn't allow you to upgrade major versions like that 😞 I have removed the 2.0.0 tag and changed it to 1.13.0 instead (and released 1.13.1 with some minor fixes).

**Comment by thomasvvugt** [comment]
No problem, thanks for the quick response! 😊
